sudo: required
language: generic

services:
  - docker
#run the tests
#start
before_install:
  - docker build -t matelb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matelb/react-test npm test
#end

#matelb porque asi se llama el dockerId
after_success:
  - docker build -t matelb/multi-client ./client
  - docker build -t matelb/multi-nginx ./nginx
  - docker build -t matelb/multi-server ./server
  - docker build -t matelb/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push matelb/multi-client
  - docker push matelb/multi-nginx
  - docker push matelb/multi-server
  - docker push matelb/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-course"
  env: "Multidockercourse-env"
  bucket_name: "elasticbeanstalk-us-east-2-679253514327"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
